// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOCk0K2hPZV75zPL769dn4eHiE3ZTLro',
    appId: '1:218371854036:android:9aef34caa12000f95f3541',
    messagingSenderId: '218371854036',
    projectId: 'pandowo-pintar-app',
    databaseURL: 'https://pandowo-pintar-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pandowo-pintar-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_sOrwdQ6Mwm7JTBruvm07XE947zu6UfM',
    appId: '1:218371854036:web:d52a33f74b99293b5f3541',
    messagingSenderId: '218371854036',
    projectId: 'pandowo-pintar-app',
    authDomain: 'pandowo-pintar-app.firebaseapp.com',
    databaseURL: 'https://pandowo-pintar-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pandowo-pintar-app.firebasestorage.app',
  );

}